pos_im_path = './human-detector/data/images/pos'
neg_im_path = './human-detector/data/images/neg'
min_wdw_sz = [68, 124]
step_size = [10, 10]
orientations = 9
pixels_per_cell = [6, 6]
cells_per_block = [2, 2]
visualize = False
normalize = True
block_normalization = 'L2-Hys'
pos_feat_ph = './human-detector/data/features/pos'
neg_feat_ph = './human-detector/data/features/neg'
model_path = './human-detector/data/models/'
threshold = .3
